name: Tagging
on:
  pull_request:
    types:
      - closed
jobs:
  tag_repo:
    name: Get tag version from branch name and tag the current code snapshot
    runs-on: ubuntu-latest
    if_merged:
      if: github.event.pull_request.merged == true
      steps:
        - uses: actions/checkout@v2

        - name: Set output
          id: vars
          run: echo ::set-output name=short_ref::${GITHUB_REF_NAME##*/}

        - name: Check Output
          run: echo ${{ steps.vars.outputs.short_ref}}

        - name: Tag and push current repo code
          run: |
            git tag ${{ steps.vars.outputs.short_ref}}
            git push origin ${{steps.vars.outputs.short_ref}}